organization: dapr
defaultSticker: clmjkxscc122740fl0mkmb7egi
stickers:
  -
    id: clmjkxscc122740fl0mkmb7egi
    alias: ghc2023

organization: dapr
defaultSticker: clrqfdv4x24910fl5n4iwu5oa
stickers:
  -
    id: clrqfdv4x24910fl5n4iwu5oa
    alias: sdk-badge